# Generated by Django 5.0.4 on 2024-04-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('present_address', models.CharField(max_length=50)),
                ('permanent_address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('', ''), ('male', 'MALE'), ('female', 'FEMALE'), ('unspecified', 'UNSPECIFIED')], default='', max_length=15)),
                ('image', models.FileField(upload_to='photo/')),
            ],
        ),
    ]
